# Generated by Django 4.1.7 on 2023-03-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_rename_name_task_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2003-02-12'),
            preserve_default=False,
        ),
    ]
